const restaurants = [
    {
        id: 1,
        name: "Meghana Foods",
        cuisines: ["Biryani", "North Indian", "Asian"],
        rating: 4.4,
        deliveryTime: "38 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 2,
        name: "Paradise Biryani",
        cuisines: ["Biryani", "Indian", "Kebabs"],
        rating: 4.2,
        deliveryTime: "42 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 3,
        name: "Domino's Pizza",
        cuisines: ["Pizza", "Fast Food", "Italian"],
        rating: 4.1,
        deliveryTime: "30 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 4,
        name: "Punjabi Dhaba",
        cuisines: ["North Indian", "Punjabi"],
        rating: 4.3,
        deliveryTime: "35 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 5,
        name: "KFC",
        cuisines: ["Fast Food", "American"],
        rating: 4.0,
        deliveryTime: "28 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 6,
        name: "Haldiram's",
        cuisines: ["Indian", "Desserts", "Snacks"],
        rating: 4.5,
        deliveryTime: "40 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 7,
        name: "Burger King",
        cuisines: ["Burgers", "Fast Food"],
        rating: 4.2,
        deliveryTime: "25 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 8,
        name: "McDonald's",
        cuisines: ["Burgers", "Fast Food"],
        rating: 4.1,
        deliveryTime: "22 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 9,
        name: "Subway",
        cuisines: ["Healthy", "Sandwiches"],
        rating: 4.3,
        deliveryTime: "27 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 10,
        name: "Pizza Hut",
        cuisines: ["Pizza", "Fast Food"],
        rating: 4.0,
        deliveryTime: "30 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 11,
        name: "Theobroma",
        cuisines: ["Desserts", "Bakery"],
        rating: 4.6,
        deliveryTime: "35 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    },
    {
        id: 12,
        name: "Bikanervala",
        cuisines: ["Indian", "Snacks", "Desserts"],
        rating: 4.5,
        deliveryTime: "37 mins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fm3rs3g6z7ibfhesmxnu",
    }
];


export default restaurants